version: '3.9'

services:
  web:
    image: dostrelith/docker-hy
    ports:
      - 4000:80
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
